#!/system/bin/sh
#=======================================#
#VARIABLES===============================#
BB=/data/adb/magisk/busybox
CLOG=/data/media/0/YourBLchanges.log
ZLOG=/data/media/0/YourBLchanges.log
BRANCH="Z-EU-compatible-mode-only-when-issue"
#=======================================#
#=======================================#

kmsg3() {
	echo -e "[*] $@" >> $CLOG
}

sleep 1

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/bleu.sh /data/adb/modules/butterlimitsforop7poos11uni/bl.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/zbleuoff.sh /data/adb/modules/butterlimitsforop7poos11uni/zbloff.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/zbbeuoff.sh /data/adb/modules/butterlimitsforop7poos11uni/zbboff.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/zeuon.sh /data/adb/modules/butterlimitsforop7poos11uni/zon.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/zbleuoff.sh /data/adb/modules/butterlimitsforop7poos11uni/post-fs-data.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/blbbeu.sh /data/adb/modules/butterlimitsforop7poos11uni/blbb.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/blexteu.sh /data/adb/modules/butterlimitsforop7poos11uni/blext.sh

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/serviceeu.sh /data/adb/modules/butterlimitsforop7poos11uni/service.sh

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/system/etc/mkadp/eu/module.prop /data/adb/modules/butterlimitsforop7poos11uni

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/system/etc/mkadp/eu/* /data/adb/modules/butterlimitsforop7poos11uni/system/etc/mkadp/


kmsg3 $(date)
kmsg3 "EU Compatible Mode On"
kmsg3 "ButterLimits Enabled"
kmsg3 "----"

$BB cp -rf /data/media/0/YourBLchanges.log /data/data/com.mkadp.blapp/files/YourBLchanges.log

$BB rm -rf /cache/*	
$BB rm -rf /data/dalvik-cache/*

sleep 1

am start -a android.intent.action.MAIN -e toasttext "EU Mode Enabled. Rebooting device in 5 secs" -n mkadp.toast/.MainActivity
sleep 1
am start -a android.intent.action.MAIN -e toasttext "After Reboot, please wait for atleast 5 minutes before unlocking it." -n mkadp.toast/.MainActivity
sleep 1
am start -a android.intent.action.MAIN -e toasttext "After Reboot, please wait for atleast 5 minutes before unlocking it." -n mkadp.toast/.MainActivity
sleep 1
am start -a android.intent.action.MAIN -e toasttext "After Reboot, please wait for atleast 5 minutes before unlocking it." -n mkadp.toast/.MainActivity
sleep 1
am start -a android.intent.action.MAIN -e toasttext "After Reboot, please wait for atleast 5 minutes before unlocking it." -n mkadp.toast/.MainActivity
sleep 1
am start -a android.intent.action.MAIN -e toasttext "After Reboot, please wait for atleast 5 minutes before unlocking it." -n mkadp.toast/.MainActivity
sleep 2

am start -a android.intent.action.MAIN -e toasttext "Rebooting Now..." -n mkadp.toast/.MainActivity

sleep 2

reboot
